neclust(kmeans)
neclust(pam)
neclust(clara)
neclust(fanny)
neclust(hcut)

nsilclust(kmeans)
nsilclust(pam)
nsilclust(clara)

ngsclust(kmeans)

nnbclust("kmeans")
nnbclust("ward.D")
nnbclust("ward.D2")
nnbclust("single")
nnbclust("complete")
nnbclust("average")
nnbclust("mcquitty")
nnbclust("median")
nnbclust("centroid")


nnclclust("pam")
nnclclust("clara")
nnclclust("hierarchical")
nnclclust("diana")
nnclclust("fanny")
nnclclust("model")
nnclclust("sota")
nnclclust("agnes")
